# Numpy Series-2

In [67]:
import numpy as  np
arr = np.array([[1,2,30],[4,5,6],[7,8,9]])
arr.dtype
arr

array([[ 1,  2, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [37]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
ar2 = np.array([[7,8],[9,10],[11,12]])

ar2 + 10 -5  +2

array([[14, 15],
       [16, 17],
       [18, 19]])

In [50]:
arr.size

6

In [70]:
np.sqrt(arr)

array([[1.        , 1.41421356, 5.47722558],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [71]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 